apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
  namespace: default
spec:
 acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: trongkd@fsoft.com.vn
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
    - http01:
       ingress:
         class: nginx