apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend
stringData:
  db.host: 10.0.11.57
  db.user: vineyard
  db.password: Fpt@2023
  db.database: vineyard
  db.port: "3306"
  host.server: https://test.vineyard.work
  path.config.oci: /home/app/config
  profile: DEFAULT
  namespace: idapel7w8ikn
  public.bucket: vineyard-upload-pub-test
  private.bucket: vineyard-upload-test
  region: us-ashburn-1
  cache.expire: "1440"
  api.base.url: https://test.vineyard.work
  redis.host: redis-master.database.svc.cluster.local
  redis.port: "6379"
  redis.password: dCSTALfueF
  tiwllio.phone-number: "+15856485388"
  tiwllio.accout-id: "ACc953db729a5cd0ffb871f4f6ab94b911"
  tiwllio.auth-token: 1056dd4875c6f4a5902fdbb402a07b5d